### ISSUE TITLE
Not in scope: type constructor or class ‘TreeNode’

### ISSUE THREAD

**Issue by scottrobertladd** [flannelhead/blackstar#3]
I'm getting an error trying to compile the HEAD pull for blackstar. I've only been doing Haskell for a few months, so I may be missing something obvious. Everything else moved smoothly, and googling "TreeNode haskell" hasn't been useful.

Preprocessing library blackstar-0.1.0.0...
[1 of 4] Compiling Color            ( src/Color.hs, dist/build/Color.o )
[2 of 4] Compiling ConfigFile       ( src/ConfigFile.hs, dist/build/ConfigFile.o )
[3 of 4] Compiling StarMap          ( src/StarMap.hs, dist/build/StarMap.o )

src/StarMap.hs:23:21:
    Not in scope: type constructor or class ‘TreeNode’
cabal: Error: some packages failed to install:
blackstar-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by flannelhead** [comment]
Are you using [`stack`](http://docs.haskellstack.org/en/stable/README/) or building this directly with `cabal`? The origin of this error message is the package [kdt](https://hackage.haskell.org/package/kdt) which I had to [fork](https://github.com/flannelhead/kdt) to expose the `TreeNode` datatype to be able to serialize it.

There's a [configuration file](https://github.com/flannelhead/blackstar/blob/master/stack.yaml) in this repo which will tell `stack` to use my fork instead of the upstream one, but obviously `cabal` won't take this in account. I highly recommend you to take a look at `stack`. I'll try and figure out if plain `cabal` can be pointed to the forked `kdt`, but this will take a while.

**Comment by giogadi** [comment]
Alternatively, I've just updated the kdt library on hackage so that the latest version allows flannelhead's code to run without modification.

**Comment by flannelhead** [comment]
Thank you @giogadi! @scottrobertladd, I will soon (in a day or two) add dependency constraints to the config file such that the build with `cabal` will be more reliable. I'll also add build instructions.

**Comment by flannelhead** [comment]
@scottrobertladd Now you can find build instructions for `cabal` in the [README](https://github.com/flannelhead/blackstar/blob/master/README.md). Start with a fresh checkout of this repo and you should be good to go. There have also been kind of many improvements in the code meanwhile. Good luck! Please report if you experience any problems.
